// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQF6S0yAwgK5k9uJOEO9gqfntU7Bf9dI',
    appId: '1:658182732511:web:96762d40c6010c89a0c76a',
    messagingSenderId: '658182732511',
    projectId: 'studymatchyapp',
    authDomain: 'studymatchyapp.firebaseapp.com',
    storageBucket: 'studymatchyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZEC-A9nLmOdOaIDqhINekJueL_ty9rQ',
    appId: '1:658182732511:android:8a5b7a2054b6d36ba0c76a',
    messagingSenderId: '658182732511',
    projectId: 'studymatchyapp',
    storageBucket: 'studymatchyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_jzFKRPj_TCpRI0aX6gUrJoBZs4K2Ws',
    appId: '1:658182732511:ios:ad2f1636e6a88584a0c76a',
    messagingSenderId: '658182732511',
    projectId: 'studymatchyapp',
    storageBucket: 'studymatchyapp.appspot.com',
    iosBundleId: 'com.example.studymatchyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_jzFKRPj_TCpRI0aX6gUrJoBZs4K2Ws',
    appId: '1:658182732511:ios:2e475c466622ee08a0c76a',
    messagingSenderId: '658182732511',
    projectId: 'studymatchyapp',
    storageBucket: 'studymatchyapp.appspot.com',
    iosBundleId: 'com.example.studymatchyapp.RunnerTests',
  );
}
